# Generated by Django 3.1.5 on 2021-01-08 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('bio', models.TextField(blank=True, max_length=800, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/')),
                ('is_listed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50, verbose_name='Nome do local')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=5)),
                ('complement', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30, verbose_name='Bairro')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('RJ', 'Rio de Janeiro')], default='RJ', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
