# Generated by Django 3.1.5 on 2021-01-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=450)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_images/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('price_from', models.FloatField()),
                ('price_sale', models.FloatField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=450)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_images/%Y/%m/')),
                ('price', models.FloatField()),
                ('price_sale', models.FloatField(blank=True, null=True)),
                ('in_stock', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
