# Generated by Django 3.1.5 on 2021-01-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210108_1748'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/%Y/%m/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicar?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_from',
            field=models.FloatField(verbose_name='Preco de base'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Preco promocional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.store', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(max_length=250, verbose_name='Resumo'),
        ),
    ]
