# Generated by Django 3.1.5 on 2021-01-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210108_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(max_length=450, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
