# Generated by Django 3.1.5 on 2021-01-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210108_1853'),
        ('products', '0003_auto_20210108_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='items', to='categories.Category'),
        ),
    ]
